import "./globals.css";
import type { Metadata, Viewport } from "next";
import { SessionProvider } from "@/components/SessionProvider";

export const metadata: Metadata = {
  title: "Backstop",
  description: "Operations platform for independent baseball coaches.",
  applicationName: "Backstop",
  // Next.js auto-injects <link rel="manifest"> from this entry; the file is
  // generated by app/manifest.ts.
  manifest: "/manifest.webmanifest",
  // iOS-specific home-screen behavior: full-screen with a translucent status
  // bar so our dark theme bleeds under the notch.
  appleWebApp: {
    capable: true,
    statusBarStyle: "black-translucent",
    title: "Backstop",
  },
  formatDetection: {
    telephone: false,
  },
};

// Viewport is a separate export in Next 14. viewportFit "cover" is what
// pairs with the iOS safe-area insets used by the body padding rule below.
export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 5,
  viewportFit: "cover",
  themeColor: "#0a0a0a",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <SessionProvider>{children}</SessionProvider>
      </body>
    </html>
  );
}
